export const CONSTANTS = {
  FORM_URL_AI_ASSISTANT: process.env.NEXT_PUBLIC_LMF_URL_ASSISTANT_IA,
  STRIPE_WEBSITE_FORMATION_URL:
    process.env.NEXT_PUBLIC_STRIPE_FORMATION_SITE_WEB_URL,
  STRIPE_WEBSITE_CLE_MAIN_URL: process.env.NEXT_PUBLIC_STRIPE_SITE_CLE_MAIN_URL,
};
